// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojhkekavmsrhfbtcblgk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qaGtla2F2bXNyaGZidGNibGdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI4OTU3NTEsImV4cCI6MjA0ODQ3MTc1MX0.YG30-nnNNyMseJ6pAM53ud-mx-ECInhbnRIsq8hXrG4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);